[tasks.doc]
env = { "RUSTDOCFLAGS" = "--html-in-header katex-header.html" }
command = "cargo"
args = ["doc", "--no-deps"]

[tasks.doc-open]
command = "open"
args = ["./target/doc/acm/index.html"]

[tasks.all]
dependencies = [
    "doc",
	"doc-open"
]

